[tool.commitizen]
changelog_file = "CHANGELOG.md"
changelog_incremental = true
tag_format = "v$major.$minor.$patch$prerelease"
update_changelog_on_bump = false
version = "0.5.1"
version_files = [
    "setup.py"
]